services:
  # 后端服务
  rollcall:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rollcall
    ports:
      - "80:80"
    environment:
      - PYTHONPATH=/app
      - DB_FILE=data/rollcall.db
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=123456
    volumes:
      - ./data:/app/data
    restart: unless-stopped